import Freska from "../assets/Freska.png";

const locations = ["Jakarta", "Surabaya", "Bandung", "Yogyakarta", "Medan"];
const prices = [
  "10 Jt",
  "15 Jt",
  "20 Jt",
  "25 Jt",
  "30 Jt",
  "35 Jt",
  "40 Jt",
  "45 Jt",
  "50 Jt",
  "55 Jt",
  "60 Jt",
  "65 Jt",
  "70 Jt",
];

const getRandomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];

export const dataAgency = [
  {
    nameCategory: "Full Service Agenchy",
    description: "A collection of full service agencies.",
    image: "",
    agencies: Array.from({ length: 22 }).map((_, i) => ({
      id: i + 1,
      nameCompany: `Paragon ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Full Service Agenchy",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "Wedding Organizer - WO",
    description: "A collection of Wedding Organizer - WO.",
    image: Freska,
    agencies: Array.from({ length: 25 }).map((_, i) => ({
      id: 23 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Wedding Organizer - WO",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "EO Spesialis MICE",
    description: "A collection of EO Spesialis MICE.",
    image: Freska,
    agencies: Array.from({ length: 20 }).map((_, i) => ({
      id: 48 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "EO Spesialis MICE",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "Social Event Organizer",
    description: "A collection of Social Event Organizer.",
    image: Freska,
    agencies: Array.from({ length: 17 }).map((_, i) => ({
      id: 68 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Social Event Organizer",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "EO Virtual & Hybrid",
    description: "A collection of EO Virtual & Hybrid.",
    image: Freska,
    agencies: Array.from({ length: 20 }).map((_, i) => ({
      id: 85 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "EO Virtual & Hybrid",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "Brand Activation Agency",
    description: "A collection of Brand Activation Agency.",
    image: Freska,
    agencies: Array.from({ length: 20 }).map((_, i) => ({
      id: 85 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Brand Activation Agency",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "Brand Activation Agency",
    description: "A collection of Brand Activation Agency.",
    image: Freska,
    agencies: Array.from({ length: 20 }).map((_, i) => ({
      id: 85 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Brand Activation Agency",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
  {
    nameCategory: "Sport Event Organizer",
    description: "A collection of Sport Event Organizer.",
    image: Freska,
    agencies: Array.from({ length: 20 }).map((_, i) => ({
      id: 85 + i,
      nameCompany: `Agency ${i + 1}`,
      description: `Bunga Mekar adalah Event Organizer spesialis pernikahan yang menghadirkan konsep intimate, elegan, hingga megah sesuai impian Anda. Kami percaya bahwa setiap kisah cinta itu unik, dan momen sakral Anda layak dirayakan dengan penuh kehangatan, keindahan, dan kesempurnaan.`,
      image: Freska,
      address: getRandomElement(locations),
      amountRiview: 2000,
      category: "Sport Event Organizer",
      price: getRandomElement(prices),
      rating: i == 2 ? 4 : 5,
    })),
  },
];
